# This file is part of CPAchecker,
# a tool for configurable software verification:
# https://cpachecker.sosy-lab.org
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

include: /build/gitlab-ci.yml

variables:
  PROJECT_PATH: "sosy-lab/software/cpachecker"
  GH_REF: "github.com/sosy-lab/cpachecker"
  # Version of https://gitlab.com/sosy-lab/software/refaster/ to use
  REFASTER_REPO_REVISION: 673d65a54133408a2936656271aa67b9aa4035fe
  # Needs to be synchronized with Error Prone version in lib/ivy.xml
  REFASTER_VERSION: 2.4.0


.binary_check: &binary_check
  stage: checks

.configuration-checks: &configuration-checks
  <<: *binary_check
  script: "ant $ANT_PROPS_CHECKS configuration-checks"
  artifacts:
    paths:
      - "ConfigurationChecks.html"
      - "hs_err_pid*.log"
    when: always
    reports:
      junit: "output/configuration-checks/TESTS-TestSuites.xml"

configuration-checks:jdk-11:
  <<: *configuration-checks
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11
  image: ${CI_REGISTRY_IMAGE}/test:jdk-11

configuration-checks:jdk-14:
  <<: *configuration-checks
  dependencies:
    - build-dependencies
    - build:jdk-14
  needs:
    - build-dependencies
    - build:jdk-14
  image: ${CI_REGISTRY_IMAGE}/test:jdk-14

configuration-documentation:
  <<: *binary_check
  script:
    - "cp doc/ConfigurationOptions.txt doc/ConfigurationOptions.txt.old"
    - "ant $ANT_PROPS_CHECKS build-documentation"
    - "diff doc/ConfigurationOptions.txt.old doc/ConfigurationOptions.txt"
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11


configuration-plot:
  stage: checks
  script:
    - "mkdir -p output"
    - "touch output/AssumptionAutomaton.txt"
    - "scripts/configViz.py > ConfigurationPlot.dot"
    - "dot -Tsvg ConfigurationPlot.dot -O"
  dependencies: []
  needs: []
  artifacts:
    paths:
      - "ConfigurationPlot.dot.svg"


forbidden-apis:
  <<: *binary_check
  script: "ant $ANT_PROPS_CHECKS forbiddenapis"
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11


.python-unit-tests: &python-unit-tests
  <<: *binary_check
  script: "ant $ANT_PROPS_CHECKS python-unit-tests"

python-unit-tests:jdk-11:
  <<: *python-unit-tests
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11
  image: ${CI_REGISTRY_IMAGE}/test:jdk-11

python-unit-tests:jdk-14:
  <<: *python-unit-tests
  dependencies:
    - build-dependencies
    - build:jdk-14
  needs:
    - build-dependencies
    - build:jdk-14
  image: ${CI_REGISTRY_IMAGE}/test:jdk-14

javascript-unit-tests:
  stage: checks
  dependencies: []
  image: ${CI_REGISTRY_IMAGE}/test:node
  before_script:
    - cd src/org/sosy_lab/cpachecker/core/counterexample/
    - npm install
  script:
    - npm test
  cache:
    paths:
    - "src/org/sosy_lab/cpachecker/core/counterexample/node_modules/"
  artifacts:
    paths:
      - src/org/sosy_lab/cpachecker/core/counterexample/unit_testing_report.html
    when: always


build-docker:test:java-node:
  extends: .build-docker
  variables:
    DOCKERFILE: build/gitlab-ci.Dockerfile.java-node
    IMAGE: /test:java-node

build-docker:test:java-node:
  extends: .build-docker
  variables:
    DOCKERFILE: build/gitlab-ci.Dockerfile.node
    IMAGE: /test:node

build-docker:release:
  extends: .build-docker
  variables:
    DOCKERFILE: build/Dockerfile.release
    IMAGE: ":1.9.1"
    EXTRA_ARGS: "--destination $CI_REGISTRY_IMAGE:latest"


javascript-e2e-tests:
  stage: checks
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11
  image: ${CI_REGISTRY_IMAGE}/test:java-node
  before_script:
      # generate example report
    - scripts/cpa.sh -predicateAnalysis test/programs/simple/SSAMap-bug.c
    - cd src/org/sosy_lab/cpachecker/core/counterexample/
    - npm install
    - "./node_modules/protractor/node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome $(dpkg-query --showformat='${Version}' --show chromium-browser)"
  script:
    - npm run e2e-test
  cache:
    paths:
    - src/org/sosy_lab/cpachecker/core/counterexample/node_modules/
  artifacts:
    paths:
      - output/Counterexample.1.html
      - src/org/sosy_lab/cpachecker/core/counterexample/e2e-tests-report
    when: always


# Checks for Python code
check-format-python:
  stage: checks
  dependencies: []
  needs: []
  image: python
  before_script:
    - pip install black
  script:
    - black . --check --diff

flake8:
  stage: checks
  dependencies: []
  needs: []
  image: python
  before_script:
    - pip install 'isort<5' # workaround for https://github.com/gforcada/flake8-isort/issues/88
    - pip install flake8-awesome
  script:
    - flake8


build-tar:
  stage: checks
  dependencies:
    - build-dependencies
    - build:jdk-11
  needs:
    - build-dependencies
    - build:jdk-11
  script: "ant $ANT_PROPS_CHECKS dist-unix -Dnamet=cpachecker"
  artifacts:
    paths:
      - "cpachecker.tar.bz2"
  only:
    refs:
      - trunk

deploy-docker:
  stage: deploy
  dependencies:
    - build-tar
  extends: .build-docker
  variables:
    DOCKERFILE: build/Dockerfile.dev
    IMAGE: ":dev"
    EXTRA_ARGS: "--context dir://."
  only:
    refs:
      - trunk


# No coverage is computed for CPAchecker
unit-tests:jdk-11:
  script: "ant $ANT_PROPS_CHECKS unit-tests"
  artifacts:
    reports:
      junit: "output/junit/TESTS-TestSuites.xml"

unit-tests:jdk-14:
  script: "ant $ANT_PROPS_CHECKS unit-tests"
  artifacts:
    reports:
      junit: "output/junit/TESTS-TestSuites.xml"


# Disable some checks because they are not used for CPAchecker
check-format:
  only: []

javadoc:
  only: []
